### ISSUE TITLE
fish

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#54]
of course
a fish out of water
should spawn a water block where it is

**Comment by Mercerenies** [comment]
Remember how it rains pufferfish every day at noon?

**Comment by EvanSkiStudios** [comment]
okay so make an exception for pufferfish
or dont worry about it

**Comment by Mercerenies** [comment]
This one is going to be fun. So any fish creates water whenever they take drowning or dryout damage (because Minecraft sometimes treats "fish-out-of-water" as drowning and sometimes as dryout, inconsistently). Pufferfish are immune to those damage types, so they're excluded for free. When you see a skeleton spawn a fish from an arrow, you have roughly five seconds to kill it before it turns into a waterfall.

**Comment by EvanSkiStudios** [comment]
https://youtu.be/9Yw5jkAHgME
