### ISSUE TITLE
weather effects temp status

### ISSUE THREAD

**Issue by EvanSkiStudios** [Mercerenies/a-turtles-troll#66]
using https://papermc.io/javadocs/paper/1.13/org/bukkit/WeatherType.html

you should be able to check the current weather

doing so, rain should prevent you from burning when hot

maybe you could do something about rain as well, but it seems rain and show are just bundled together as "downfall"

**Comment by Mercerenies** [comment]
Solved by 8ec000b. Rain and snow now prevent the burning effect in hot biomes (excluding biomes where it doesn't rain, of course).

I can differentiate between rain and snow, since Minecraft makes that determination using the temperature (snow is < 0.15, rain is 0.15 < x < 0.95, and no weather at > 0.95), so if you have any ideas for rain/snow, I'm all ears.
